const filterActionTypes = {
  UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
  FILTER_BY_NAME: "FILTER_BY_NAME",
  FILTER_BY_TYPE: "FILTER_BY_TYPE",
  FILTER_BY_PRICE: "FILTER_BY_PRICE",
  FILTER_BY_GLUTEN: "FILTER_BY_GLUTEN"
};

export default filterActionTypes;
